"""Remove unique name of the name column in the projects table

Revision ID: 485b8a3cddf7
Revises: 49743111e0d7
Create Date: 2024-09-21 16:33:05.932827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485b8a3cddf7'
down_revision: Union[str, None] = '49743111e0d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
