"""Remove index of the name column in the projects table

Revision ID: 909f70e3d59b
Revises: 485b8a3cddf7
Create Date: 2024-09-21 16:38:34.172721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '909f70e3d59b'
down_revision: Union[str, None] = '485b8a3cddf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
